version: "3.8"
services:
  setup_php:
    depends_on:
      - setup_db
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./config:/usr/local/etc/php
  setup_db:
    image: mysql:5.7

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myUserPass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myUser

volumes:
  html: {}