version: "3.8"
services:
  php:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./html:/var/www/html
      - ./config:/usr/local/etc/php
  db:
    image: mysql:5.7

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myUserPass
      MYSQL_DATABASE: mydb
      MYSQL_USER: myUser
      MYSQL_PASSWORD: myUser

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: myUserPass
volumes:
  html: {}