<div class="columns">
    <?php
    foreach ($datos as $item) {
        echo "<div class='column'>
                <div class='box'>
                    <article class='media'>
                        <div class='media-left'>
                            <figure class='image is-64x64'>
                                <img src='https://bulma.io/images/placeholders/128x128.png' alt='Image'>
                            </figure>
                        </div>
                        <div class='media-content'>
                            <div class='content'>
                                <p>
                                    <strong>" . $item->names . "</strong> <small>@johnsmith</small> <small>31m</small>
                                    <br>
                                    " . $item->code . "
                                </p>
                            </div>
                        </div>
                    </article>
                </div>
            </div>";
    }
    ?>
</div>


